### ISSUE TITLE
AngelChest text persists after chest opening

### ISSUE THREAD

**Issue by MercerK** [JEFF-Media-GbR/Spigot-AngelChest#12]
We have two incidents of AngelChests' text persisting after the chest is opened. One was by a player who died underwater several days ago, and another one was when I died at spawn due to falling from the sky.

https://imgur.com/a/YS0KWPb

https://imgur.com/a/otvLsqa

I had items when I died. When I opened the chest, it was empty. Destroyed the chest and the text persisted. 

Not sure how to get rid of the text....

EDIT: The text still persists when I disable the plugin...
EDIT2: For those having similar issues, I used this `/minecraft:kill @e[type=armor_stand]` when next to it. It'll need to be modified to kill only those within a radius, versus all loaded.

**Comment by mfnalex** [comment]
Does this issue still exist?

**Comment by Cobecc** [comment]
The issue still exist :( I come here for the same issue. I dont know how to erase the text @mfnalex  Any suggestion ? And I cant use the command /minecraft:kill #e [type=armor_stand] because I'm not sure if that command erase any unloaded and loaded armor stand in the server and have any problem with the users.

Edit: I try to use the /minecraft:kill @e[type=minecraft:armor_stand, distance=1] (distances = ex radius) and the responce is  Entity not found

**Comment by Cobecc** [comment]
Find the solution! A moderator of my server he use : /minecraft:kill @e[type=armor_stand,distance=..3] 
the points are the key apparenly

bye!

**Comment by mfnalex** [comment]
I am very sorry for the late reply. Yes, it is of course to possible to delete the text with the mentioned command. However, actually this problem should not exist at all. If the situation repeats, please tell me. I am sure I can find a solution so that this problem will no longer occur. Thank you for your patience.
